#!/usr/bin/env bash
set -Eeuo pipefail

###############################################################################
# EdgeGuard R3 candidate publish / pre-hardware preflight
#
# Usage:
#   ./publish-r3-candidate.sh VERSION BUILD_ID
#
# Example:
#   ./publish-r3-candidate.sh \
#       1.2.2 \
#       rk3588-r3g-1.2.2-001
#
# Responsibilities:
#   - validate build-r3-candidate.sh evidence
#   - validate final rootfs release + baked server URL
#   - publish the exact signed bundle to permanent OTA server
#   - switch/restart permanent server
#   - verify exact live manifest
#   - perform one full HTTP bundle hash/byte closure
#
# Explicitly NOT done:
#   - Buildroot/rootfs rebuild
#   - bundle rebuild
#   - Range/416/report regression
#   - RK3588 modification/install/reboot
#   - Git checks
###############################################################################

fail()
{
    echo "publish-r3-candidate: FAIL: $*" >&2
    exit 1
}

trap 'rc=$?; echo "publish-r3-candidate: failed rc=$rc line=$LINENO" >&2' ERR

[ "$#" -eq 2 ] || {
    echo "usage: $0 VERSION BUILD_ID" >&2
    exit 2
}

REQUEST_VERSION="$1"
REQUEST_BUILD_ID="$2"

###############################################################################
# Fixed environment
###############################################################################

REPO="${EDGEGUARD_REPO:-/home/liu2004/work/EG_OTA}"

SDK="${EDGEGUARD_SDK:-/home/liu2004/work/Linux_SDK/atk_dlrk3588_linux5.10}"

ARTIFACT_ROOT="${EDGEGUARD_ARTIFACT_ROOT:-$HOME/work/EG_OTA-artifacts}"

SERVER_ROOT="${EDGEGUARD_SERVER_ROOT:-/opt/edgeguard-ota}"
SERVER_CONFIG="$SERVER_ROOT/app/config.py"
SERVER_SERVICE="${EDGEGUARD_SERVER_SERVICE:-edgeguard-ota.service}"

ARTIFACT_DIR="$ARTIFACT_ROOT/${REQUEST_VERSION}__${REQUEST_BUILD_ID}"
CANDIDATE_ENV="$ARTIFACT_DIR/candidate.env"

EXPECTED_BUNDLE="$ARTIFACT_DIR/update-${REQUEST_VERSION}.raucb"

EVIDENCE="/tmp/edgeguard-publish-${REQUEST_VERSION}__${REQUEST_BUILD_ID}"

rm -rf "$EVIDENCE"
mkdir -p "$EVIDENCE"

###############################################################################
# Argument validation
###############################################################################

[[ "$REQUEST_VERSION" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]] ||
    fail "VERSION must be canonical MAJOR.MINOR.PATCH"

[[ "$REQUEST_BUILD_ID" =~ ^[A-Za-z0-9._+-]+$ ]] ||
    fail "invalid BUILD_ID syntax"

###############################################################################
# Required tools/files
###############################################################################

for cmd in \
    sha256sum \
    stat \
    cmp \
    debugfs \
    python3 \
    curl \
    ip \
    systemctl \
    journalctl
do
    command -v "$cmd" >/dev/null 2>&1 ||
        fail "required command missing: $cmd"
done

[ -f "$CANDIDATE_ENV" ] ||
    fail "candidate.env missing: $CANDIDATE_ENV"

echo
echo "============================================================"
echo "0. LOAD CANDIDATE EVIDENCE"
echo "============================================================"

# candidate.env is generated by build-r3-candidate.sh itself using printf %q.
# It is a trusted local build artifact, not network input.
# shellcheck disable=SC1090
source "$CANDIDATE_ENV"

[ "${VERSION:-}" = "$REQUEST_VERSION" ] ||
    fail "candidate.env VERSION mismatch"

[ "${BUILD_ID:-}" = "$REQUEST_BUILD_ID" ] ||
    fail "candidate.env BUILD_ID mismatch"

[ "${BUNDLE:-}" = "$EXPECTED_BUNDLE" ] ||
    fail "candidate.env BUNDLE path mismatch"

for name in \
    ROOTFS \
    ROOTFS_SIZE \
    ROOTFS_SHA256 \
    BOOT_IMG \
    BOOT_SIZE \
    BOOT_SHA256 \
    BUNDLE \
    BUNDLE_SIZE \
    BUNDLE_SHA256
do
    [ -n "${!name:-}" ] ||
        fail "candidate.env missing $name"
done

printf 'VERSION=%s\n' "$VERSION"
printf 'BUILD_ID=%s\n' "$BUILD_ID"
printf 'ROOTFS=%s\n' "$ROOTFS"
printf 'BOOT_IMG=%s\n' "$BOOT_IMG"
printf 'BUNDLE=%s\n' "$BUNDLE"

###############################################################################
# Candidate bytes must still match candidate.env
###############################################################################

echo
echo "============================================================"
echo "1. CANDIDATE BYTE EVIDENCE"
echo "============================================================"

[ -f "$ROOTFS" ] ||
    fail "rootfs missing: $ROOTFS"

[ -f "$BOOT_IMG" ] ||
    fail "boot.img missing: $BOOT_IMG"

[ -f "$BUNDLE" ] ||
    fail "bundle missing: $BUNDLE"

actual_rootfs_size="$(stat -Lc '%s' "$ROOTFS")"
actual_rootfs_sha="$(sha256sum "$ROOTFS" | awk '{print $1}')"

actual_boot_size="$(stat -Lc '%s' "$BOOT_IMG")"
actual_boot_sha="$(sha256sum "$BOOT_IMG" | awk '{print $1}')"

actual_bundle_size="$(stat -Lc '%s' "$BUNDLE")"
actual_bundle_sha="$(sha256sum "$BUNDLE" | awk '{print $1}')"

echo "ROOTFS_SIZE=$actual_rootfs_size"
echo "ROOTFS_SHA256=$actual_rootfs_sha"

echo "BOOT_SIZE=$actual_boot_size"
echo "BOOT_SHA256=$actual_boot_sha"

echo "BUNDLE_SIZE=$actual_bundle_size"
echo "BUNDLE_SHA256=$actual_bundle_sha"

[ "$actual_rootfs_size" = "$ROOTFS_SIZE" ] ||
    fail "rootfs size differs from candidate.env"

[ "$actual_rootfs_sha" = "$ROOTFS_SHA256" ] ||
    fail "rootfs SHA256 differs from candidate.env"

[ "$actual_boot_size" = "$BOOT_SIZE" ] ||
    fail "boot size differs from candidate.env"

[ "$actual_boot_sha" = "$BOOT_SHA256" ] ||
    fail "boot SHA256 differs from candidate.env"

[ "$actual_bundle_size" = "$BUNDLE_SIZE" ] ||
    fail "bundle size differs from candidate.env"

[ "$actual_bundle_sha" = "$BUNDLE_SHA256" ] ||
    fail "bundle SHA256 differs from candidate.env"

if [ -f "${BUNDLE}.size" ]; then
    recorded_size="$(tr -d '[:space:]' < "${BUNDLE}.size")"
    [ "$recorded_size" = "$BUNDLE_SIZE" ] ||
        fail ".raucb.size mismatch"
fi

if [ -f "${BUNDLE}.sha256" ]; then
    recorded_sha="$(awk '{print $1}' "${BUNDLE}.sha256")"
    [ "$recorded_sha" = "$BUNDLE_SHA256" ] ||
        fail ".raucb.sha256 mismatch"
fi

echo "CANDIDATE_BYTE_EVIDENCE=PASS"

###############################################################################
# Signed RAUC info produced by mandatory build-time RAUC verification
###############################################################################

echo
echo "============================================================"
echo "2. SIGNED BUNDLE IDENTITY EVIDENCE"
echo "============================================================"

INFO="${BUNDLE}.info"

[ -f "$INFO" ] ||
    fail "signed bundle info missing: $INFO"

python3 - \
    "$INFO" \
    "$VERSION" \
    "$BUILD_ID" \
    "$ROOTFS_SHA256" \
    "$ROOTFS_SIZE" \
    "$BOOT_SHA256" \
    "$BOOT_SIZE" <<'PY'
import sys

(
    path,
    expected_version,
    expected_build,
    expected_rootfs_sha,
    expected_rootfs_size,
    expected_boot_sha,
    expected_boot_size,
) = sys.argv[1:]

data = {}

with open(path, encoding="utf-8") as f:
    for raw in f:
        line = raw.rstrip("\n")
        if "=" not in line:
            continue

        key, value = line.split("=", 1)

        if value.startswith("'") and value.endswith("'"):
            value = value[1:-1]

        data[key] = value

def require(key, expected):
    actual = data.get(key)
    if actual != expected:
        raise SystemExit(
            "{} mismatch: actual={!r} expected={!r}".format(
                key, actual, expected
            )
        )

require(
    "RAUC_MF_COMPATIBLE",
    "EdgeGuard-ATK-DLRK3588-RK3588",
)
require("RAUC_MF_VERSION", expected_version)
require("RAUC_MF_BUILD", expected_build)
require("RAUC_MF_IMAGES", "2")
require("RAUC_MF_FILES", "0")

classes = []

for i in range(2):
    cls = data.get("RAUC_IMAGE_CLASS_{}".format(i))
    name = data.get("RAUC_IMAGE_NAME_{}".format(i))
    digest = data.get("RAUC_IMAGE_DIGEST_{}".format(i))
    size = data.get("RAUC_IMAGE_SIZE_{}".format(i))

    if cls is None:
        raise SystemExit("missing RAUC image class {}".format(i))

    classes.append(cls)

    if cls == "rootfs":
        if name != "rootfs.ext4":
            raise SystemExit("unexpected rootfs image filename")
        if digest != expected_rootfs_sha:
            raise SystemExit("signed rootfs digest mismatch")
        if size != expected_rootfs_size:
            raise SystemExit("signed rootfs size mismatch")

    elif cls == "boot":
        if name != "boot.img":
            raise SystemExit("unexpected boot image filename")
        if digest != expected_boot_sha:
            raise SystemExit("signed boot digest mismatch")
        if size != expected_boot_size:
            raise SystemExit("signed boot size mismatch")

    else:
        raise SystemExit("unexpected image class: {!r}".format(cls))

if sorted(classes) != ["boot", "rootfs"]:
    raise SystemExit(
        "signed image classes are not exactly rootfs + boot"
    )

print("SIGNED_BUNDLE_IDENTITY=PASS")
print("SIGNED_ROOTFS_BYTES=PASS")
print("SIGNED_BOOT_BYTES=PASS")
PY

###############################################################################
# Read actual final rootfs — never trust source agent.conf for this gate
###############################################################################

echo
echo "============================================================"
echo "3. FINAL ROOTFS RELEASE / AGENT CONFIG"
echo "============================================================"

debugfs \
    -R 'cat /etc/edgeguard-ota/release.json' \
    "$ROOTFS" \
    2>/dev/null \
    > "$EVIDENCE/release.json"

debugfs \
    -R 'cat /etc/edgeguard-ota/agent.conf' \
    "$ROOTFS" \
    2>/dev/null \
    > "$EVIDENCE/agent.conf"

echo "--- release.json ---"
cat "$EVIDENCE/release.json"

echo
echo "--- agent.conf ---"
cat "$EVIDENCE/agent.conf"

python3 - \
    "$EVIDENCE/release.json" \
    "$EVIDENCE/agent.conf" \
    "$VERSION" \
    "$BUILD_ID" \
    "$EVIDENCE/server.env" <<'PY'
import configparser
import ipaddress
import json
import sys
from urllib.parse import urlsplit

release_path, conf_path, version, build_id, output = sys.argv[1:]

with open(release_path, encoding="utf-8") as f:
    actual_release = json.load(f)

expected_release = {
    "schema_version": 1,
    "device_compatible": "atk-dlrk3588",
    "rauc_compatible": "EdgeGuard-ATK-DLRK3588-RK3588",
    "version": version,
    "build_id": build_id,
}

if actual_release != expected_release:
    print("actual release  =", actual_release)
    print("expected release=", expected_release)
    raise SystemExit("final rootfs release identity mismatch")

cfg = configparser.ConfigParser(interpolation=None)

with open(conf_path, encoding="utf-8") as f:
    cfg.read_file(f)

base_url = cfg.get("server", "base_url")

try:
    parsed = urlsplit(base_url)
    port = parsed.port
except ValueError as exc:
    raise SystemExit("invalid base_url: {}".format(exc))

if parsed.scheme != "http":
    raise SystemExit("R3 campaign base_url must use http")

if parsed.username is not None or parsed.password is not None:
    raise SystemExit("userinfo is forbidden in base_url")

if parsed.path not in ("", "/"):
    raise SystemExit("base_url must not contain a path")

if parsed.query or parsed.fragment:
    raise SystemExit("base_url must not contain query/fragment")

if port != 8000:
    raise SystemExit(
        "permanent OTA server port must be 8000"
    )

try:
    addr = ipaddress.ip_address(parsed.hostname or "")
except ValueError:
    raise SystemExit(
        "R3 hardware campaign base_url must use an IPv4 address"
    )

if addr.version != 4:
    raise SystemExit("base_url is not IPv4")

with open(output, "w", encoding="utf-8") as f:
    f.write("BASE_URL={}\n".format(base_url))
    f.write("SERVER_IP={}\n".format(addr))
    f.write("SERVER_PORT={}\n".format(port))

print("FINAL_IMAGE_RELEASE_IDENTITY=PASS")
print("FINAL_IMAGE_SERVER_URL=PASS")
print("BASE_URL={}".format(base_url))
print("SERVER_IP={}".format(addr))
PY

# shellcheck disable=SC1090
source "$EVIDENCE/server.env"

###############################################################################
# Candidate points at this host's currently assigned Wi-Fi/LAN IPv4
###############################################################################

echo
echo "============================================================"
echo "4. LOCAL SERVER NETWORK IDENTITY"
echo "============================================================"

ip -4 -br addr

if ! ip -4 -o addr show \
    | awk '{print $4}' \
    | cut -d/ -f1 \
    | grep -Fxq "$SERVER_IP"
then
    fail "candidate base_url IP $SERVER_IP is not assigned to this host"
fi

SERVER_IF="$(
    ip -4 -o addr show \
        | awk -v ip="$SERVER_IP" '
            {
                split($4, a, "/")
                if (a[1] == ip) {
                    print $2
                    exit
                }
            }
        '
)"

[ -n "$SERVER_IF" ] ||
    fail "cannot resolve interface for $SERVER_IP"

echo "SERVER_INTERFACE=$SERVER_IF"
echo "SERVER_IP=$SERVER_IP"
echo "BASE_URL=$BASE_URL"
echo "LOCAL_SERVER_NETWORK_IDENTITY=PASS"

###############################################################################
# Publish bundle atomically
###############################################################################

echo
echo "============================================================"
echo "5. PUBLISH SIGNED BUNDLE"
echo "============================================================"

SERVER_ARTIFACT_DIR="$SERVER_ROOT/artifacts/versions/$VERSION"
SERVER_BUNDLE="$SERVER_ARTIFACT_DIR/update.raucb"
SERVER_TMP="$SERVER_ARTIFACT_DIR/.update.raucb.publish.$$"

sudo mkdir -p "$SERVER_ARTIFACT_DIR"
sudo rm -f "$SERVER_TMP"

sudo install \
    -m 0644 \
    "$BUNDLE" \
    "$SERVER_TMP"

tmp_size="$(sudo stat -Lc '%s' "$SERVER_TMP")"
tmp_sha="$(sudo sha256sum "$SERVER_TMP" | awk '{print $1}')"

echo "STAGED_SERVER_SIZE=$tmp_size"
echo "STAGED_SERVER_SHA256=$tmp_sha"

[ "$tmp_size" = "$BUNDLE_SIZE" ] ||
    fail "staged server bundle size mismatch"

[ "$tmp_sha" = "$BUNDLE_SHA256" ] ||
    fail "staged server bundle SHA256 mismatch"

# Same directory/filesystem: rename publishes the completely written file.
sudo mv -f "$SERVER_TMP" "$SERVER_BUNDLE"

server_size="$(sudo stat -Lc '%s' "$SERVER_BUNDLE")"
server_sha="$(sudo sha256sum "$SERVER_BUNDLE" | awk '{print $1}')"

[ "$server_size" = "$BUNDLE_SIZE" ] ||
    fail "published bundle size mismatch"

[ "$server_sha" = "$BUNDLE_SHA256" ] ||
    fail "published bundle SHA256 mismatch"

echo "SERVER_BUNDLE=$SERVER_BUNDLE"
echo "SERVER_BUNDLE_SHA256=$server_sha"
echo "SERVER_BUNDLE_PUBLISH=PASS"

###############################################################################
# Idempotently switch permanent server release
###############################################################################

echo
echo "============================================================"
echo "6. UPDATE PERMANENT SERVER CONFIG"
echo "============================================================"

[ -f "$SERVER_CONFIG" ] ||
    fail "server config missing: $SERVER_CONFIG"

sudo python3 - \
    "$SERVER_CONFIG" \
    "$VERSION" \
    "$BUILD_ID" <<'PY'
from pathlib import Path
import os
import re
import stat
import sys

path = Path(sys.argv[1])
version = sys.argv[2]
build_id = sys.argv[3]

text = path.read_text(encoding="utf-8")

# Protocol invariants. This publisher does not silently rewrite them.
required = [
    '    schema_version: int = 1',
    '    device_compatible: str = "atk-dlrk3588"',
    '    artifact_url: str = "/update.raucb"',
    '    mandatory: bool = False',
]

for line in required:
    if text.count(line) != 1:
        raise SystemExit(
            "server protocol invariant missing/duplicated: {!r}".format(line)
        )

updates = [
    (
        r'(?m)^    version: str = "[^"]+"$',
        '    version: str = "{}"'.format(version),
        "version",
    ),
    (
        r'(?m)^    build_id: str = "[^"]+"$',
        '    build_id: str = "{}"'.format(build_id),
        "build_id",
    ),
    (
        r'(?m)^    artifact_path: Path = .+$',
        (
            '    artifact_path: Path = PROJECT_ROOT / '
            '"artifacts" / "versions" / "{}" / "update.raucb"'
        ).format(version),
        "artifact_path",
    ),
]

for pattern, replacement, name in updates:
    text, count = re.subn(pattern, replacement, text)

    if count != 1:
        raise SystemExit(
            "{} assignment count={}".format(name, count)
        )

st = path.stat()

tmp = path.with_name(path.name + ".publish.tmp")

with open(tmp, "w", encoding="utf-8") as f:
    f.write(text)
    f.flush()
    os.fsync(f.fileno())

os.chmod(tmp, stat.S_IMODE(st.st_mode))
os.replace(tmp, path)

dirfd = os.open(str(path.parent), os.O_RDONLY)

try:
    os.fsync(dirfd)
finally:
    os.close(dirfd)

print("SERVER_CONFIG_UPDATE=PASS")
PY

sudo grep -E \
    'schema_version|device_compatible|version:|build_id|artifact_url|artifact_path|mandatory' \
    "$SERVER_CONFIG"

###############################################################################
# Restart and wait for the actual application manifest
###############################################################################

echo
echo "============================================================"
echo "7. RESTART / WAIT FOR PERMANENT SERVER"
echo "============================================================"

sudo systemctl restart "$SERVER_SERVICE"

READY_MANIFEST="$EVIDENCE/ready-manifest.json"

ready=0

for attempt in $(seq 1 30); do
    if curl \
        --noproxy '*' \
        --silent \
        --show-error \
        --connect-timeout 2 \
        --max-time 5 \
        http://127.0.0.1:8000/manifest.json \
        -o "$READY_MANIFEST" \
        2>/dev/null
    then
        if python3 - \
            "$READY_MANIFEST" \
            "$VERSION" \
            "$BUILD_ID" \
            "$BUNDLE_SHA256" \
            "$BUNDLE_SIZE" <<'PY'
import json
import sys

path, version, build, sha256, size = sys.argv[1:]

with open(path, encoding="utf-8") as f:
    actual = json.load(f)

expected = {
    "schema_version": 1,
    "device_compatible": "atk-dlrk3588",
    "version": version,
    "build_id": build,
    "artifact_url": "/update.raucb",
    "sha256": sha256,
    "size": int(size),
    "mandatory": False,
}

raise SystemExit(0 if actual == expected else 1)
PY
        then
            ready=1
            break
        fi
    fi

    sleep 1
done

[ "$ready" = 1 ] ||
    fail "permanent server did not expose exact candidate manifest"

systemctl is-active "$SERVER_SERVICE" >/dev/null ||
    fail "permanent server is not active"

echo "--- live manifest ---"
cat "$READY_MANIFEST"
echo

echo "--- recent service log ---"

journalctl \
    -u "$SERVER_SERVICE" \
    --since '-3 minutes' \
    --no-pager \
    -n 80

echo "SERVER_APPLICATION_READY=PASS"
echo "SERVER_MANIFEST_EXACT=PASS"

###############################################################################
# Wi-Fi/LAN manifest closure using the endpoint baked into the candidate image
###############################################################################

echo
echo "============================================================"
echo "8. CANDIDATE-ENDPOINT MANIFEST CLOSURE"
echo "============================================================"

HTTP_MANIFEST="$EVIDENCE/http-manifest.json"

manifest_code="$(
    curl \
        --noproxy '*' \
        --silent \
        --show-error \
        --connect-timeout 5 \
        --max-time 30 \
        --output "$HTTP_MANIFEST" \
        --write-out '%{http_code}' \
        "$BASE_URL/manifest.json"
)"

echo "MANIFEST_HTTP_CODE=$manifest_code"

[ "$manifest_code" = 200 ] ||
    fail "candidate endpoint manifest did not return HTTP 200"

python3 - \
    "$HTTP_MANIFEST" \
    "$VERSION" \
    "$BUILD_ID" \
    "$BUNDLE_SHA256" \
    "$BUNDLE_SIZE" <<'PY'
import json
import sys

path, version, build, sha256, size = sys.argv[1:]

with open(path, encoding="utf-8") as f:
    actual = json.load(f)

expected = {
    "schema_version": 1,
    "device_compatible": "atk-dlrk3588",
    "version": version,
    "build_id": build,
    "artifact_url": "/update.raucb",
    "sha256": sha256,
    "size": int(size),
    "mandatory": False,
}

if actual != expected:
    print("actual   =", actual)
    print("expected =", expected)
    raise SystemExit("candidate endpoint manifest mismatch")

print("CANDIDATE_ENDPOINT_MANIFEST=PASS")
PY

###############################################################################
# One full HTTP bundle closure
###############################################################################

echo
echo "============================================================"
echo "9. FULL HTTP BUNDLE HASH / BYTE CLOSURE"
echo "============================================================"

HTTP_BUNDLE="$EVIDENCE/http-update.raucb"

bundle_code="$(
    curl \
        --noproxy '*' \
        --silent \
        --show-error \
        --connect-timeout 5 \
        --max-time 900 \
        --output "$HTTP_BUNDLE" \
        --write-out '%{http_code}' \
        "$BASE_URL/update.raucb"
)"

echo "BUNDLE_HTTP_CODE=$bundle_code"

[ "$bundle_code" = 200 ] ||
    fail "candidate endpoint bundle did not return HTTP 200"

http_size="$(stat -Lc '%s' "$HTTP_BUNDLE")"
http_sha="$(sha256sum "$HTTP_BUNDLE" | awk '{print $1}')"

echo "HTTP_BUNDLE_SIZE=$http_size"
echo "HTTP_BUNDLE_SHA256=$http_sha"

[ "$http_size" = "$BUNDLE_SIZE" ] ||
    fail "HTTP bundle size mismatch"

[ "$http_sha" = "$BUNDLE_SHA256" ] ||
    fail "HTTP bundle SHA256 mismatch"

cmp -s "$BUNDLE" "$HTTP_BUNDLE" ||
    fail "HTTP bundle is not byte-identical to candidate bundle"

echo "HTTP_BUNDLE_BYTE_IDENTICAL=PASS"

###############################################################################
# Final result
###############################################################################

echo
echo "============================================================"
echo "R3 CANDIDATE PUBLISH / PRE-HARDWARE RESULT"
echo "============================================================"

echo "VERSION=$VERSION"
echo "BUILD_ID=$BUILD_ID"
echo "BASE_URL=$BASE_URL"
echo "SERVER_INTERFACE=$SERVER_IF"
echo "BUNDLE_SIZE=$BUNDLE_SIZE"
echo "BUNDLE_SHA256=$BUNDLE_SHA256"

echo
echo "CANDIDATE_BYTE_EVIDENCE=PASS"
echo "SIGNED_BUNDLE_IDENTITY=PASS"
echo "FINAL_IMAGE_RELEASE_IDENTITY=PASS"
echo "FINAL_IMAGE_SERVER_URL=PASS"
echo "LOCAL_SERVER_NETWORK_IDENTITY=PASS"
echo "SERVER_BUNDLE_PUBLISH=PASS"
echo "SERVER_CONFIG_UPDATE=PASS"
echo "SERVER_APPLICATION_READY=PASS"
echo "SERVER_MANIFEST_EXACT=PASS"
echo "CANDIDATE_ENDPOINT_MANIFEST=PASS"
echo "HTTP_BUNDLE_BYTE_IDENTICAL=PASS"

echo
echo "EVIDENCE_DIR=$EVIDENCE"
echo "PUBLISH_R3_CANDIDATE_RC=0"
