[system]
compatible=EdgeGuard-ATK-DLRK3588-RK3588
bootloader=custom
statusfile=/userdata/edgeguard-remote-ota/rauc-status.raucs

[keyring]
path=/etc/rauc/keyring.pem
check-purpose=codesign

[handlers]
bootloader-custom-backend=/usr/libexec/rauc/edgeguard-rk-ab-backend

[slot.rootfs.0]
device=/dev/disk/by-partlabel/system_a
type=ext4
bootname=a
readonly=true

[slot.boot.0]
device=/dev/disk/by-partlabel/boot_a
type=raw
parent=rootfs.0
readonly=true

[slot.rootfs.1]
device=/dev/disk/by-partlabel/system_b
type=ext4
bootname=b
readonly=true

[slot.boot.1]
device=/dev/disk/by-partlabel/boot_b
type=raw
parent=rootfs.1
readonly=true